# Configuration to file watcher
file-watcher:
  path: /data/in/
  pathWriter: /data/out/
  thread-pool: 4
  chunk.size: 1000

spring:
  batch:
    initializer:
      enabled: false
    job:
      enabled: false
  application:
    name: analyzer-batch
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:analyzerBatch;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: true
    h2:
      console:
        enabled: true