# Configuração do file watcher
file-watcher:
  path: /root/data/in/
  thread-pool: 4
  chunk.size: 1000

spring:
  batch:
    initializer:
      enabled: false
    job:
      enabled: false
  application:
    name: batch-analyzer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:processfiledb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    hikari:
      poolName: Hikari
      auto-commit: true
    h2:
      console:
        enabled: true